# COLUMNS:
#   id: int64
#   title: object
#   genre: object
#   original_language: object
#   overview: object
#   popularity: float64
#   release_date: object
#   vote_count: int64

# TARGET_COLUMN:
#   name: vote_average


movies:
  columns:
    movieId: int
    title: str
    genres: str

ratings:
  columns:
    userId: int
    rating: float
    timestamp: int
    movieId: int
  rating_range:
    min_value: 0.5
    max_value: 5.0

tags:
  columns:
    userId: int
    timestamp: int
    tag: str
    movieId: int
