COLUMNS:
  id: int64
  title: object
  genre: object
  original_language: object
  overview: object
  popularity: float64
  release_date: object
  vote_count: int64

TARGET_COLUMN:
  name: vote_average